# Generated by Django 4.2 on 2023-04-21 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('color', models.CharField(choices=[('green', 'Green'), ('blue', 'Blue'), ('yellow', 'Yellow'), ('red', 'Red')], default='green', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remind_at', models.DateTimeField()),
                ('email_notification', models.BooleanField(default=False)),
                ('note', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='notes.note')),
            ],
        ),
    ]
