# Generated by Django 4.2 on 2023-05-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='remind_before',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reminder',
            name='repeat',
            field=models.CharField(choices=[('none', 'None'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='none', max_length=10),
        ),
    ]
