# Generated by Django 4.2 on 2023-05-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_reminder_remind_before_reminder_repeat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='repeat',
            field=models.CharField(choices=[('none', 'Not set'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='none', max_length=10),
        ),
    ]
