# Generated by Django 4.2 on 2023-05-26 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_reminder_repeat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='remind_before',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='repeat',
        ),
    ]
