# Generated by Django 4.2 on 2023-05-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_remove_reminder_remind_before_remove_reminder_repeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='user_timezone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
