# Generated by Django 4.2 on 2023-05-28 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_reminder_user_timezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='user_timezone',
        ),
    ]
