# Generated by Django 4.2 on 2023-05-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reminder_intervals',
            field=models.JSONField(default=dict),
        ),
    ]
