# Generated by Django 4.2 on 2023-05-10 05:08

from django.db import migrations, models
import profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_userprofile_email_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='profile/static/img/default.png', upload_to=profile.models.unique_filename),
        ),
    ]
