# Generated by Django 4.2 on 2023-05-27 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0008_alter_userprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
