# Generated by Django 4.2 on 2023-05-28 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0011_userprofile_timezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
